spring.application.name=portfolio-manager

# Conexao postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio-manager
spring.datasource.username=postgres
spring.datasource.password=postgres

# Spring MVC
spring.mvc.format.date=yyyy-MM-dd
spring.jpa.open-in-view=false

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mock external member API base URL (same application)
member.api.base-url=http://localhost:8081

# Springdoc / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Server
server.port=8081
